### PR TITLE
fix bug and rollback libs after libcheck

### PR DESCRIPTION
**Pull request by simskij**
This PR counters a side effect of the libchecker action that would lead to the charm being published with the latest libraries if the libschecker and the upload charm action where used as steps in the same job rather than split across multiple jobs. In addition, the libchecker action will not execute if the charm has no lib folder. 

Further, the PR fixes a possible bug that likely would ever occur in testing scenarios, where the event name of our context would be null.

### CODE REVIEW

**Review by DomFleischmann — COMMENTED** [review]
Interesting, Charmcraft seems to fail to upload a charmhub branch when we add a `/` in the git branch. That's something we should probably address.

**Review by sanchezfdezjavier — APPROVED** [review]
LGTM

**Comment by simskij** [comment]
recreating the pr with a non-slash branch name.

**Comment by simskij** [comment]
> Interesting, Charmcraft seems to fail to upload a charmhub branch when we add a `/` in the git branch. That's something we should probably address.

Split this out into https://github.com/canonical/charming-actions/issues/30

**Pull request closed without merging**
